# .streamlit/config.toml
[theme]
primaryColor = "#00b4d8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f4f8"
textColor = "#0a2342"
font = "sans serif"

[logger]
level = "info"

[client]
showErrorDetails = true

[server]
maxUploadSize = 200